spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 0a77a64cf8dcd230ec18
            client-secret: 4c2c3f8b1ece9e28f5a45502058f6859598b188c
            google:
              client-id: google-client-id
              client-secret: google-client-secret

#logging:
#  level:
#    org.springframework.security: DEBUG
